"""initial migration

Revision ID: 4229c42b3958
Revises: 
Create Date: 2026-06-04 00:23:28.753563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4229c42b3958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_uuid', sa.String(length=36), nullable=False),
    sa.Column('transcript_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_uuid')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_history_transcript_uuid'), ['transcript_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_user_uuid'), ['user_uuid'], unique=False)

    op.create_table('transcript_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_uuid')
    )
    with op.batch_alter_table('transcript_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_history_user_uuid'), ['user_uuid'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('profession', sa.String(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('transcript_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_history_user_uuid'))

    op.drop_table('transcript_history')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_chat_history_transcript_uuid'))

    op.drop_table('chat_history')
    # ### end Alembic commands ###
